name: Playwright Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🎭 Install Playwright browsers
        run: |
          playwright install --with-deps

      - name: 🧪 Run Behave tests with Allure
        run: |
          behave --tags=@login -f allure_behave.formatter:AllureFormatter -o reports/ || true

      - name: 📸 Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: 🎥 Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: videos/

      - name: 📊 Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/

      - name: 📊 Generate Allure Report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: reports
          allure_report: allure-report

      - name: 🔍 Debug files
        run: |
          ls -R

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
